language: python

python:
   - 2.7
   - 3.6

install:
  - sudo apt-get update -y
  - sudo apt-get install -y libfftw3-dev
  - pip install git+git://github.com/realfastvla/evla_mcast.git
  - pip install git+git://github.com/realfastvla/rfpipe.git
  - python setup.py install

script:
  - pytest

notifications:
  email: false
  slack: realfastvla:ID1qIFG70HGYf3G6Y3oWoFFk
